name = "distracted-drivers-tf"
repo = "https://github.com/fomorians/distracted-drivers-tf.git"
description = "State Farm Distracted Driver Challenge"
environment = "tensorflow"

[datasets]
"jim/distracted-drivers-tf" = "0.0.1"
